// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/exPriceD/pr-reviewer-service/internal/domain/repository (interfaces: PullRequestRepository)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=internal/domain/repository/mocks/pull_request_repository_mock.go github.com/exPriceD/pr-reviewer-service/internal/domain/repository PullRequestRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/exPriceD/pr-reviewer-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// CountActiveReviewsByUserIDs mocks base method.
func (m *MockPullRequestRepository) CountActiveReviewsByUserIDs(ctx context.Context, userIDs []string) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveReviewsByUserIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveReviewsByUserIDs indicates an expected call of CountActiveReviewsByUserIDs.
func (mr *MockPullRequestRepositoryMockRecorder) CountActiveReviewsByUserIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveReviewsByUserIDs", reflect.TypeOf((*MockPullRequestRepository)(nil).CountActiveReviewsByUserIDs), ctx, userIDs)
}

// CountReviewsByUserIDs mocks base method.
func (m *MockPullRequestRepository) CountReviewsByUserIDs(ctx context.Context, userIDs []string) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountReviewsByUserIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountReviewsByUserIDs indicates an expected call of CountReviewsByUserIDs.
func (mr *MockPullRequestRepositoryMockRecorder) CountReviewsByUserIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountReviewsByUserIDs", reflect.TypeOf((*MockPullRequestRepository)(nil).CountReviewsByUserIDs), ctx, userIDs)
}

// Create mocks base method.
func (m *MockPullRequestRepository) Create(ctx context.Context, pr *entity.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPullRequestRepositoryMockRecorder) Create(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullRequestRepository)(nil).Create), ctx, pr)
}

// Delete mocks base method.
func (m *MockPullRequestRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPullRequestRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPullRequestRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockPullRequestRepository) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockPullRequestRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockPullRequestRepository)(nil).Exists), ctx, id)
}

// FindByAuthorID mocks base method.
func (m *MockPullRequestRepository) FindByAuthorID(ctx context.Context, authorID string) ([]*entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAuthorID", ctx, authorID)
	ret0, _ := ret[0].([]*entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAuthorID indicates an expected call of FindByAuthorID.
func (mr *MockPullRequestRepositoryMockRecorder) FindByAuthorID(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAuthorID", reflect.TypeOf((*MockPullRequestRepository)(nil).FindByAuthorID), ctx, authorID)
}

// FindByID mocks base method.
func (m *MockPullRequestRepository) FindByID(ctx context.Context, id string) (*entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPullRequestRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPullRequestRepository)(nil).FindByID), ctx, id)
}

// FindByIDForUpdate mocks base method.
func (m *MockPullRequestRepository) FindByIDForUpdate(ctx context.Context, id string) (*entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDForUpdate", ctx, id)
	ret0, _ := ret[0].(*entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDForUpdate indicates an expected call of FindByIDForUpdate.
func (mr *MockPullRequestRepositoryMockRecorder) FindByIDForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDForUpdate", reflect.TypeOf((*MockPullRequestRepository)(nil).FindByIDForUpdate), ctx, id)
}

// FindByReviewerID mocks base method.
func (m *MockPullRequestRepository) FindByReviewerID(ctx context.Context, reviewerID string) ([]*entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReviewerID", ctx, reviewerID)
	ret0, _ := ret[0].([]*entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReviewerID indicates an expected call of FindByReviewerID.
func (mr *MockPullRequestRepositoryMockRecorder) FindByReviewerID(ctx, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReviewerID", reflect.TypeOf((*MockPullRequestRepository)(nil).FindByReviewerID), ctx, reviewerID)
}

// GetStats mocks base method.
func (m *MockPullRequestRepository) GetStats(ctx context.Context) (int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetStats indicates an expected call of GetStats.
func (mr *MockPullRequestRepositoryMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockPullRequestRepository)(nil).GetStats), ctx)
}

// MergePR mocks base method.
func (m *MockPullRequestRepository) MergePR(ctx context.Context, prID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, prID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergePR indicates an expected call of MergePR.
func (mr *MockPullRequestRepositoryMockRecorder) MergePR(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockPullRequestRepository)(nil).MergePR), ctx, prID)
}

// ReplaceReviewer mocks base method.
func (m *MockPullRequestRepository) ReplaceReviewer(ctx context.Context, prID, oldReviewerID, newReviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceReviewer", ctx, prID, oldReviewerID, newReviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceReviewer indicates an expected call of ReplaceReviewer.
func (mr *MockPullRequestRepositoryMockRecorder) ReplaceReviewer(ctx, prID, oldReviewerID, newReviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceReviewer", reflect.TypeOf((*MockPullRequestRepository)(nil).ReplaceReviewer), ctx, prID, oldReviewerID, newReviewerID)
}

// Update mocks base method.
func (m *MockPullRequestRepository) Update(ctx context.Context, pr *entity.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPullRequestRepositoryMockRecorder) Update(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPullRequestRepository)(nil).Update), ctx, pr)
}
